// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFhlyYcslJlJSYdMH_LTSckGJIcK-vxNo',
    appId: '1:1072371601182:web:f47807f0995a8b3d25830f',
    messagingSenderId: '1072371601182',
    projectId: 'ritesh-sarees',
    authDomain: 'ritesh-sarees.firebaseapp.com',
    storageBucket: 'ritesh-sarees.appspot.com',
    measurementId: 'G-T3VFNCNZ97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Jl90_e2-u8w7INtBLhuZLf8DcDrngcE',
    appId: '1:1072371601182:android:a76b45b51462abba25830f',
    messagingSenderId: '1072371601182',
    projectId: 'ritesh-sarees',
    storageBucket: 'ritesh-sarees.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnxexYHblPFQr9bW_t8ryjZDPBJRWIj2g',
    appId: '1:1072371601182:ios:1f23e93970eb29d225830f',
    messagingSenderId: '1072371601182',
    projectId: 'ritesh-sarees',
    storageBucket: 'ritesh-sarees.appspot.com',
    androidClientId: '1072371601182-sq1iufu8h2e9ccfr9uo5lv03e0c1gfqq.apps.googleusercontent.com',
    iosClientId: '1072371601182-7aded7eb9u3etk3m1sasv71d1rlas4t2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceMajorProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnxexYHblPFQr9bW_t8ryjZDPBJRWIj2g',
    appId: '1:1072371601182:ios:1f23e93970eb29d225830f',
    messagingSenderId: '1072371601182',
    projectId: 'ritesh-sarees',
    storageBucket: 'ritesh-sarees.appspot.com',
    androidClientId: '1072371601182-sq1iufu8h2e9ccfr9uo5lv03e0c1gfqq.apps.googleusercontent.com',
    iosClientId: '1072371601182-7aded7eb9u3etk3m1sasv71d1rlas4t2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceMajorProject',
  );
}
