// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcjWLnOshtyqO-nfPtawf2WAdhulNWqaI',
    appId: '1:221309136169:web:c63b77eae3441d69ff9b38',
    messagingSenderId: '221309136169',
    projectId: 'ecommerce-b2c-a6083',
    authDomain: 'ecommerce-b2c-a6083.firebaseapp.com',
    storageBucket: 'ecommerce-b2c-a6083.appspot.com',
    measurementId: 'G-6KP8HBN4P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMyH27AJo9U06SYx-ClPbKHTK4pU4DSRk',
    appId: '1:221309136169:android:ba47a932fe7ba4bcff9b38',
    messagingSenderId: '221309136169',
    projectId: 'ecommerce-b2c-a6083',
    storageBucket: 'ecommerce-b2c-a6083.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRhJKSUXVyaeNdvzzlMghErbnssicK_jY',
    appId: '1:221309136169:ios:38c68d6b031bd2bcff9b38',
    messagingSenderId: '221309136169',
    projectId: 'ecommerce-b2c-a6083',
    storageBucket: 'ecommerce-b2c-a6083.appspot.com',
    iosClientId: '221309136169-in79m3455pks3j2illg0hrjod7r8gqaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceMajorProject',
  );
}
